begin;
-- Schema guard
create schema if not exists public;
-- Stores (cửa hàng/chi nhánh) - thay thế dữ liệu tĩnh hiện tại
create table if not exists public.stores (
    id bigint generated by default as identity primary key,
    name text not null,
    image text,
    address text not null,
    phone text,
    opening_hours text,
    -- ví dụ: "08:00-21:00"
    location jsonb,
    -- { lat: number, lng: number }
    is_active boolean default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);
comment on table public.stores is 'Danh sách cửa hàng/điểm nhận (pickup). Dùng map cho orders.station_id';
-- updated_at trigger (idempotent)
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now();
return new;
end;
$$;
drop trigger if exists trg_stores_updated_at on public.stores;
create trigger trg_stores_updated_at before
update on public.stores for each row execute procedure public.set_updated_at();
-- RLS: deny direct access from client. Chỉ cho phép gọi RPC
alter table public.stores enable row level security;
do $$ begin execute 'revoke all on table public.stores from public, anon, authenticated';
exception
when others then null;
end $$;
do $$ begin execute 'grant select, insert, update, delete on table public.stores to service_role';
exception
when others then null;
end $$;
drop policy if exists "stores_deny_all_select" on public.stores;
drop policy if exists "stores_deny_all_modify" on public.stores;
create policy "stores_deny_all_select" on public.stores for
select using (false);
create policy "stores_deny_all_modify" on public.stores for all using (false) with check (false);
-- RPCs
-- Danh sách cửa hàng đang hoạt động
create or replace function public.rpc_list_stores() returns setof public.stores language sql stable security definer
set search_path = public as $$
select *
from public.stores
where is_active is true
order by id asc;
$$;
-- Lấy chi tiết cửa hàng theo id
create or replace function public.rpc_get_store(p_id bigint) returns public.stores language sql stable security definer
set search_path = public as $$
select *
from public.stores
where id = p_id;
$$;
-- Thêm/sửa cửa hàng (dùng cho admin UI nếu cần)
create or replace function public.rpc_upsert_store(
        p_name text,
        p_address text,
        p_image text default null,
        p_phone text default null,
        p_opening_hours text default null,
        p_location jsonb default null,
        p_is_active boolean default true,
        p_id bigint default null
    ) returns public.stores language plpgsql security definer
set search_path = public as $$
declare v public.stores;
begin if p_id is null then
insert into public.stores(
        name,
        address,
        image,
        phone,
        opening_hours,
        location,
        is_active
    )
values (
        p_name,
        p_address,
        nullif(p_image, ''),
        nullif(p_phone, ''),
        nullif(p_opening_hours, ''),
        p_location,
        coalesce(p_is_active, true)
    )
returning * into v;
else
update public.stores
set name = coalesce(nullif(p_name, ''), name),
    address = coalesce(nullif(p_address, ''), address),
    image = coalesce(nullif(p_image, ''), image),
    phone = coalesce(nullif(p_phone, ''), phone),
    opening_hours = coalesce(nullif(p_opening_hours, ''), opening_hours),
    location = coalesce(p_location, location),
    is_active = coalesce(p_is_active, is_active),
    updated_at = now()
where id = p_id
returning * into v;
end if;
return v;
end;
$$;
-- Grants
do $$ begin execute 'revoke all on function public.rpc_list_stores() from public';
execute 'revoke all on function public.rpc_get_store(bigint) from public';
execute 'revoke all on function public.rpc_upsert_store(text, text, text, text, text, jsonb, boolean, bigint) from public';
exception
when others then null;
end $$;
do $$ begin execute 'grant execute on function public.rpc_list_stores() to anon';
execute 'grant execute on function public.rpc_get_store(bigint) to anon';
-- upsert chỉ bật nếu bạn muốn sửa trực tiếp từ client
execute 'grant execute on function public.rpc_upsert_store(text, text, text, text, text, jsonb, boolean, bigint) to anon';
exception
when others then null;
end $$;
commit;